language: node_js
node_js:
 - "12"
before_install:
 - npm install -g eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node

script:
 - npm test
notifications:
  email:
    - jtrs@incowia.com
    - pwr@incowia.com
    - hrbu@incowia.com
