language: node_js
node_js:
 - "6"
before_install:
 - npm install -g eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise

script:
 - npm test
notifications:
  email:
    - jtrs@incowia.com
    - pwr@incowia.com
    - hrbu@incowia.com
